# Generated by Django 3.0.8 on 2020-08-03 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=120, null=True)),
                ('channel_taken', models.CharField(max_length=120, null=True)),
                ('channel_taken_id', models.CharField(max_length=120, null=True)),
                ('title', models.CharField(max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp_save', models.DateTimeField(auto_now_add=True, null=True)),
                ('followed', models.BooleanField(default=False)),
                ('unfollowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_account', models.CharField(max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('account_followers', models.DecimalField(decimal_places=0, default=0, max_digits=100000, null=True)),
                ('account_followers_followed', models.DecimalField(decimal_places=0, default=0, max_digits=100000, null=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_follows_per_day', models.CharField(max_length=120, null=True)),
                ('max_follows_per_day', models.CharField(max_length=120, null=True)),
                ('min_waiting_time', models.CharField(max_length=120, null=True)),
                ('max_waiting_time', models.CharField(max_length=120, null=True)),
                ('unfollow_per_follow', models.CharField(max_length=120, null=True)),
                ('min_days_to_unfollow', models.CharField(max_length=120, null=True)),
                ('instagram_account', models.CharField(max_length=120, null=True)),
                ('instagram_password', models.CharField(max_length=120, null=True)),
                ('daily_posts', models.CharField(max_length=120, null=True)),
                ('time_lapse_posting', models.CharField(max_length=120, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
