# Generated by Django 3.0.8 on 2020-08-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_source_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='user',
        ),
        migrations.AddField(
            model_name='source',
            name='created_by',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
