# Generated by Django 3.0.8 on 2020-08-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_auto_20200805_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='source',
        ),
        migrations.AddField(
            model_name='follow',
            name='created_by',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
