# Generated by Django 3.0.8 on 2020-08-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_auto_20200805_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_taken', models.CharField(max_length=120, null=True)),
                ('channel_taken_id', models.CharField(max_length=120, null=True)),
                ('title', models.CharField(max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp_save', models.DateTimeField(auto_now_add=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=120, null=True)),
                ('channel_account', models.CharField(max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
