# Generated by Django 3.0.8 on 2020-08-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_content_source_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_taken', models.CharField(max_length=120, null=True)),
                ('channel_taken_id', models.CharField(max_length=120, null=True)),
                ('title', models.CharField(max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp_save', models.DateTimeField(auto_now_add=True, null=True)),
                ('times_used', models.CharField(max_length=120, null=True)),
                ('created_by', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_taken', models.CharField(max_length=120, null=True)),
                ('channel_taken_id', models.CharField(max_length=120, null=True)),
                ('title', models.CharField(max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp_save', models.DateTimeField(auto_now_add=True, null=True)),
                ('times_used', models.CharField(max_length=120, null=True)),
                ('created_by', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
