# Generated by Django 3.0.8 on 2020-08-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_description_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='channel_taken',
        ),
        migrations.RemoveField(
            model_name='description',
            name='channel_taken_id',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='channel_taken',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='channel_taken_id',
        ),
    ]
