# Generated by Django 3.0.8 on 2020-08-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_auto_20200806_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='progress',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
