# Generated by Django 3.0.8 on 2020-08-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_source_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='caption',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='displayUrl',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='hashtags',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='id_instagram',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='mentions',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='timestamp',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='type_content',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='url_list',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
