# Generated by Django 3.0.8 on 2020-08-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0010_auto_20200807_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='hashtags_per_post',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
