# Generated by Django 3.0.8 on 2020-08-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0011_settings_hashtags_per_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='api_key',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='dataset_id',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='source_content',
            name='request',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='source_content',
            name='request_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
