# Generated by Django 3.0.8 on 2020-08-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0012_auto_20200809_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='source_content',
            name='request_number',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
