# Generated by Django 3.0.8 on 2020-08-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0013_source_content_request_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='source_content',
            name='status',
            field=models.CharField(choices=[('1', 'Requested, waiting for dataset to be uploaded'), ('2', 'Dataset uploaded. Please proceed to click on scrape button'), ('3', 'Dataset scraped')], default='1', max_length=120),
        ),
    ]
