# Generated by Django 3.0.8 on 2020-08-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0014_source_content_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source_content',
            name='status',
        ),
    ]
