# Generated by Django 3.0.8 on 2020-08-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0015_remove_source_content_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='source_content',
            name='status',
            field=models.CharField(choices=[('Requested, waiting for dataset to be uploaded', 'Requested, waiting for dataset to be uploaded'), ('Dataset uploaded. Please proceed to click on scrape button', 'Dataset uploaded. Please proceed to click on scrape button'), ('Dataset used', 'Dataset used')], default='Requested, waiting for dataset to be uploaded', max_length=120),
        ),
    ]
