# Generated by Django 3.0.8 on 2020-08-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0016_source_content_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='dataset_id',
        ),
        migrations.AddField(
            model_name='source_content',
            name='api_key',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='source_content',
            name='dataset_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
