# Generated by Django 3.0.8 on 2020-08-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0017_auto_20200810_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='source_content',
            name='quantity_contents',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
