# Generated by Django 3.0.8 on 2020-08-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0018_source_content_quantity_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='channel_taken_id',
        ),
        migrations.AddField(
            model_name='content',
            name='engagement',
            field=models.DecimalField(decimal_places=2, max_digits=10000, null=True),
        ),
    ]
