# Generated by Django 3.0.8 on 2020-08-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0019_auto_20200812_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp_save', models.DateTimeField(auto_now_add=True, null=True)),
                ('followers', models.CharField(max_length=120, null=True)),
                ('contents', models.CharField(max_length=120, null=True)),
                ('contents_used', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
