# Generated by Django 3.0.8 on 2020-08-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0020_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='created_by',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
