# Generated by Django 3.0.8 on 2020-08-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0021_accounts_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
