# Generated by Django 3.0.8 on 2020-08-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0022_delete_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='engagement',
            field=models.DecimalField(decimal_places=0, max_digits=10000, null=True),
        ),
    ]
