# Generated by Django 3.0.8 on 2020-08-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0023_auto_20200813_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='unfollow_per_follow',
            new_name='max_waiting_time_unfollow',
        ),
        migrations.AddField(
            model_name='settings',
            name='min_unfollows_per_day',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='min_waiting_time_unfollow',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
