# Generated by Django 3.0.8 on 2020-08-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0024_auto_20200813_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='min_days_to_unfollow',
            new_name='days_to_unfollow',
        ),
        migrations.AddField(
            model_name='settings',
            name='max_unfollows_per_day',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
