# Generated by Django 3.0.8 on 2020-08-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0025_auto_20200813_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='follow_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='posting_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='unfollow',
            field=models.BooleanField(default=False),
        ),
    ]
