# Generated by Django 3.0.8 on 2020-08-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0026_auto_20200814_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='engagement',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.DecimalField(decimal_places=0, max_digits=10000, null=True),
        ),
    ]
